'use strict';
const assert = require('node:assert/strict');
const { channel } = require('./release-policy.js');

// Update only the paired version guard and diagnostic emitted by the pinned CLI.
// Compare generated bytes against this expectation; never normalize the input
// artifact, which must contain the actual release version in every branch.
function loaderForVersion(reviewed, version) {
  channel(version, version.includes('-'));
  let embeddedVersion;
  return reviewed.replace(
    /(if \(bindingPackageVersion !== ')([^'\r\n]+)('(?: && process\.env\.NAPI_RS_ENFORCE_VERSION_CHECK && process\.env\.NAPI_RS_ENFORCE_VERSION_CHECK !== '0')?\) \{\n[ \t]+throw new Error\(`(?:Native|WASI) binding package version mismatch, expected )\2( but got \$\{bindingPackageVersion\}\. You can reinstall dependencies to fix this issue\.`\))/g,
    (_, guard, previous, diagnostic, suffix) => {
      embeddedVersion ??= previous;
      assert.equal(previous, embeddedVersion, 'Reviewed loader contains inconsistent package versions');
      return guard + version + diagnostic + version + suffix;
    },
  );
}
module.exports = { loaderForVersion };
