'use strict';
const assert = require('node:assert/strict');
const { channel } = require('./release-policy.js');
const fs = require('node:fs');
const { execFileSync } = require('node:child_process');

// Update only the paired version guard and diagnostic emitted by the pinned CLI.
// Compare generated bytes against this expectation; never normalize the input
// artifact, which must contain the actual release version in every branch.
function loaderForVersion(reviewed, previousVersion, version) {
  channel(previousVersion, previousVersion.includes('-'));
  channel(version, version.includes('-'));
  let count = 0;
  const expected = reviewed.replace(
    /(if \(bindingPackageVersion !== ')([^'\r\n]+)('(?: && process\.env\.NAPI_RS_ENFORCE_VERSION_CHECK && process\.env\.NAPI_RS_ENFORCE_VERSION_CHECK !== '0')?\) \{\n[ \t]+throw new Error\(`(?:Native|WASI) binding package version mismatch, expected )\2( but got \$\{bindingPackageVersion\}\. You can reinstall dependencies to fix this issue\.`\))/g,
    (_, guard, previous, diagnostic, suffix) => {
      assert.equal(previous, previousVersion, 'Tracked loader must consistently contain the PR base version');
      count++;
      return guard + version + diagnostic + version + suffix;
    },
  );
  assert.equal(count, 27, 'Expected all 27 paired version guards from the pinned napi-rs CLI; review generator changes');
  return expected;
}
function versionChanged(base, head) {
  assert.equal(head.name, base.name, 'Package identity changed; review required');
  for (const pkg of [base, head]) channel(pkg.version, pkg.version.includes('-'));
  return base.version !== head.version;
}
function validateLoader(tracked, generated, base, head) {
  assert(versionChanged(base, head), 'No package version change');
  // A reviewed, already aligned loader needs no write, even if it includes
  // intentional generator changes committed by a maintainer.
  if (generated === tracked) {
    loaderForVersion(tracked, head.version, head.version);
    return false;
  }
  assert.equal(generated, loaderForVersion(tracked, base.version, head.version),
    'Regeneration changed more than embedded package versions; review and commit binding.js manually');
  return true;
}
function inspect(mode, env = process.env) {
  assert.equal(env.GITHUB_EVENT_NAME, 'pull_request');
  const { pull_request: pr } = JSON.parse(fs.readFileSync(env.GITHUB_EVENT_PATH, 'utf8'));
  const git = args => execFileSync('git', args, { encoding: 'utf8' });
  assert.equal(git(['rev-parse', 'HEAD']).trim(), pr.head.sha, 'Checkout must match PR head');
  const base = JSON.parse(git(['show', `${pr.base.sha}:package.json`]));
  const head = JSON.parse(git(['show', 'HEAD:package.json']));
  let changed = versionChanged(base, head);
  if (mode === 'validate') {
    const modified = git(['diff', 'HEAD', '--name-only']).trim().split('\n').filter(Boolean);
    assert(modified.every(file => file === 'binding.js'), 'Generation changed tracked files other than binding.js');
    changed = validateLoader(git(['show', 'HEAD:binding.js']), fs.readFileSync('binding.js', 'utf8'), base, head);
    if (changed) {
      assert.equal(pr.head.repo.full_name, env.GITHUB_REPOSITORY,
        'Fork PR needs a loader update: regenerate and commit binding.js in the fork; automatic writes are in-repo only');
      assert.equal(pr.base.ref, 'main', 'Automatic updates require the trusted main base; review and commit binding.js manually');
    }
  } else assert.equal(mode, 'detect');
  fs.appendFileSync(env.GITHUB_OUTPUT, `changed=${changed}\n`);
}
if (require.main === module) inspect(process.argv[2]);
module.exports = { loaderForVersion, versionChanged, validateLoader, inspect };
