name: Publish GitHub Release to npm
on:
  release:
    types: [published]
permissions:
  contents: read
jobs:
  build:
    uses: ./.github/workflows/native.yml
  publish:
    needs: build
    runs-on: ubuntu-24.04
    concurrency:
      group: npm-production-publication
      cancel-in-progress: false
    environment: npm-production
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/setup-node@v7
        with:
          node-version: 26.x
          registry-url: https://registry.npmjs.org
      - run: npm install --global npm@11.19.1
      - uses: actions/download-artifact@v8
        with:
          name: npm-distribution
          path: distribution
      - name: Publish stable
        if: "!github.event.release.prerelease"
        run: npm publish "$GITHUB_WORKSPACE"/distribution/*.tgz --access public --provenance --tag latest
      - name: Publish prerelease
        if: "github.event.release.prerelease"
        run: npm publish "$GITHUB_WORKSPACE"/distribution/*.tgz --access public --provenance --tag beta
